### ISSUE TITLE
Problem with number of frames to import 

### ISSUE THREAD

**Issue by syKevinPeng** [MattiasFredriksson/io_anim_c3d#6]
Hi,
I installed the add-on successfully, but couldn't import all the frames. My c3d file contains up to 3270 frames but only the first 800 frames are loaded. Here is the file I used to import [file](https://drive.google.com/file/d/1yDilQZe03fv0X9w2GD3OIPzx_WFLGmVn/view?usp=sharing). Could you please help me to fix it?

Best,
Siyuan

**Comment by MattiasFredriksson** [comment]
Hey, will look into it tomorrow and see if I can find a solution. 

BR
Mattias

**Comment by MattiasFredriksson** [comment]
Looked into it and all frames are loaded correctly. The issue seems to be that by default the importer inserts the keyframes to match the current frame rate of the scene so that the animation playback runs in 'real time'. Since the recording is sampled at 100 Hz and the Blender frame rate by default is 24 the animation keyframes appears to be compressed on the animation timeline as roughly 4 keyframes are inserted per frame.

To import the animation with keyframes inserted in one frame increments make sure the 'Frame Rate' setting is disabled during import. Alternatively set the frame rate for the Blender scene to 100 Hz.

Hopefully it should solve the issue!

**Comment by syKevinPeng** [comment]
Really appreciate it! Will try it tonight

**Comment by syKevinPeng** [comment]
Confirmed. This resolved the problem. Thanks!
