### ISSUE TITLE
Question Regarding Marker Shape

### ISSUE THREAD

**Issue by syKevinPeng** [MattiasFredriksson/io_anim_c3d#8]
Hey,
Sorry to bother you again. First of all, I want to thank you. Your Add-on is very useful for our research project. 
However, I have a question/feature request for the add-on. Could you please add a feature to allow users to choose the shape of the marker? Right now, it's just using the default cube. Could you add an option to load marker with the sphere shape? If you don't have time to implement UI, could you tell me how to modify the source code?

best

**Comment by MattiasFredriksson** [comment]
Hey, 

There are a few ways to adjust marker shapes but it would depend on if the purpose is to 'render' the markers or if you need to change the bone handle shape.

If it is the latter one can set custom shapes per bone as described in https://docs.blender.org/manual/en/latest/animation/armatures/bones/properties/display.html. It will be cumbersome change each 'marker' (bone) by hand but one can create a script to automate the process. Not sure if it will be relevant to extend the addon as it can be done during import or from a separate script (relevance will depend on if it is possible to select a shape from the import menu).

There are a few other display modes that can be set on the armature itself but it is inflexible and using 'B-Bone' to create cubic shapes was the only display mode that was suitable for displaying 'markers' that I found.

If the purpose is to create renders from the markers then one has to use the [armature modifier](https://docs.blender.org/manual/en/latest/modeling/modifiers/deform/armature.html#:~:text=The%20Armature%20modifier%20is%20used,to%20be%20animated%20by%20hand). There should be multiple resources to describe the process better then I can do here.

Hopefully it answers your question!

**Comment by rschader** [comment]
Sorry if this is the wrong way to comment, just found this and getting it to import c3d files, etc. I have some success, and I can view the motion of the created armature, although the "bones" don't appear connected. Any tips of how I can apply all this to a character mesh or other armature? Thanks! P.S. I see you don't appear to be doing any recent updates to this addon? I would be willing to help if at all possible?

**Comment by MattiasFredriksson** [comment]
Hey @rschader, I replied to your main question in #9 as this question is unrelated to this topic. Feel free to reply there. Regarding improving the addon feel free to do so, if the intention is to add/extend features please open an issue first so it can be discussed (to ensure the feature may get accepted). This addon is however ONLY an importer it's not supposed to include features for processing the data except for the purpose of providing the data in an usable form (and it seems you are looking for something more then that). 

Regarding updates I'm working on it currently but with low priority as I'm not doing anything with animations at the moment. This might not be super obvious as I'm mostly working on improving the main dependency EmbodiedCognition/py-c3d#51 which does the actual importing. What this means for now is that the addon seems stable enough and only if there are issues reported I will correct those. I have also started to prioritize [Blender development](https://developer.blender.org/p/Osares/) rather then github projects.

Since this is off-topic from the original issue I will close this now as either the issue got resolved or the OP was unable to achieve the intended end result in Blender (as the core of the question was Blender related and not related to an issur with the addon itself).
